use alloc::boxed::Box;
use alloc::collections::BTreeMap;
use alloc::ffi::{CString, NulError};
#[cfg(test)]
use core::cell::RefCell;
#[cfg(not(test))]
use core::cell::UnsafeCell;
use core::ffi::{CStr, c_void};
#[cfg(not(test))]
use core::sync::atomic::{AtomicBool, Ordering};

use crate::c_bindings;

use super::widget::{LvObj, Widget};

// ============================================================
//  ImageSrc — source pointer for LVGL images
// ============================================================

/// A source pointer that can refer to either a C image descriptor array
/// (`const lv_image_dsc_t *`) or a file-system path string.
///
/// # Safety
///
/// LVGL does not copy the source data — the pointed-to memory must remain
/// valid for as long as the image widget exists. Safe DSL setters consume
/// `ImageSrc` and retain it until the LVGL object is deleted.
///
/// # Examples
///
/// ```ignore
/// // From a C image array generated by LVGL's image converter tool:
/// extern "C" { static my_icon: c_void; }
/// let src = unsafe { ImageSrc::descriptor(&raw const my_icon) };
///
/// // From a file path on LittleFS / FAT:
/// let src = ImageSrc::file("S:icons/logo.bin")?;
/// ```
#[derive(Clone)]
pub struct ImageSrc {
    kind: ImageSrcKind,
}

#[derive(Clone)]
enum ImageSrcKind {
    Descriptor(*const c_void),
    File(CString),
    StaticFile(&'static CStr),
}

// SAFETY: LVGL image descriptors are expected to point to immutable global data;
// file paths are either owned immutable CString buffers or static CStr literals.
unsafe impl Send for ImageSrc {}
unsafe impl Sync for ImageSrc {}

impl ImageSrc {
    /// Creates an `ImageSrc` from a pointer to a C `lv_image_dsc_t` descriptor.
    ///
    /// # Safety
    /// - `ptr` must be non-null and point to a valid `lv_image_dsc_t` that
    ///   lives at least as long as every widget that uses this source.
    /// - The pointed-to data must be safe to access from any thread
    ///   (`Send + Sync`), since `ImageSrc` implements both traits.
    #[inline]
    pub unsafe fn descriptor(ptr: *const c_void) -> Self {
        debug_assert!(
            !ptr.is_null(),
            "ImageSrc::descriptor called with null pointer"
        );
        Self {
            kind: ImageSrcKind::Descriptor(ptr),
        }
    }

    /// Creates an `ImageSrc` from a file-system path.
    ///
    /// The path is copied into an owned, NUL-terminated buffer because LVGL
    /// stores the pointer directly. Safe DSL setters retain the returned
    /// `ImageSrc` until the LVGL object is deleted.
    #[inline]
    pub fn file(path: &str) -> Result<Self, NulError> {
        Ok(Self {
            kind: ImageSrcKind::File(CString::new(path)?),
        })
    }

    /// Creates an `ImageSrc` from a static C string path without allocation.
    ///
    /// This is useful for low-level callers that already have a static C string.
    /// Most application code should use [`ImageSrc::file`] with a Rust `&str`.
    #[inline]
    pub const fn file_cstr(path: &'static CStr) -> Self {
        Self {
            kind: ImageSrcKind::StaticFile(path),
        }
    }

    /// Returns the raw pointer passed to LVGL's `lv_image_set_src` /
    /// `lv_obj_set_style_bg_image_src` calls.
    #[inline]
    pub(crate) fn as_ptr(&self) -> *const c_void {
        match &self.kind {
            ImageSrcKind::Descriptor(ptr) => *ptr,
            ImageSrcKind::File(path) => path.as_ptr().cast::<c_void>(),
            ImageSrcKind::StaticFile(path) => path.as_ptr().cast::<c_void>(),
        }
    }
}

#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) enum ImageRetentionSlot {
    Source,
    ImageButtonState(u32),
    Background,
}

type ImageRetentionKey = (usize, ImageRetentionSlot);

#[cfg(test)]
std::thread_local! {
    static IMAGE_RETENTION_STORE: RefCell<BTreeMap<ImageRetentionKey, *mut ImageSrc>> =
        RefCell::new(BTreeMap::new());
}

#[cfg(not(test))]
struct ImageRetentionStore {
    locked: AtomicBool,
    sources: UnsafeCell<Option<BTreeMap<ImageRetentionKey, *mut ImageSrc>>>,
}

#[cfg(not(test))]
// SAFETY: LVGL object APIs are only valid from the UI thread. The store is
// mutated only as part of those UI-thread calls and delete-event callbacks.
unsafe impl Sync for ImageRetentionStore {}

#[cfg(not(test))]
static IMAGE_RETENTION_STORE: ImageRetentionStore = ImageRetentionStore {
    locked: AtomicBool::new(false),
    sources: UnsafeCell::new(None),
};

#[cfg(test)]
fn with_image_retention_store<R>(
    f: impl FnOnce(&mut BTreeMap<ImageRetentionKey, *mut ImageSrc>) -> R,
) -> R {
    IMAGE_RETENTION_STORE.with(|store| f(&mut store.borrow_mut()))
}

#[cfg(not(test))]
fn with_image_retention_store<R>(
    f: impl FnOnce(&mut BTreeMap<ImageRetentionKey, *mut ImageSrc>) -> R,
) -> R {
    while IMAGE_RETENTION_STORE
        .locked
        .compare_exchange(false, true, Ordering::Acquire, Ordering::Relaxed)
        .is_err()
    {
        core::hint::spin_loop();
    }
    struct Unlock;
    impl Drop for Unlock {
        fn drop(&mut self) {
            IMAGE_RETENTION_STORE
                .locked
                .store(false, Ordering::Release);
        }
    }
    let _unlock = Unlock;

    let store = unsafe { &mut *IMAGE_RETENTION_STORE.sources.get() };
    if store.is_none() {
        *store = Some(BTreeMap::new());
    }
    f(store.as_mut().expect("image retention store initialized"))
}

pub(crate) fn set_retained_src_for_obj(
    obj: *mut c_bindings::lv_obj_t,
    slot: ImageRetentionSlot,
    src: ImageSrc,
    apply: impl FnOnce(*const c_void),
) {
    // Keep the old source alive until after LVGL is updated to the new pointer.
    let src_ptr = src.as_ptr();
    let retained = Box::into_raw(Box::new(src));
    unsafe {
        c_bindings::lv_obj_add_event_cb(
            obj,
            Some(drop_retained_image_src),
            c_bindings::LV_EVENT_DELETE,
            retained.cast::<c_void>(),
        );
    }
    let previous =
        with_image_retention_store(|store| store.insert((obj as usize, slot), retained));
    apply(src_ptr);
    if let Some(previous) = previous {
        unsafe {
            c_bindings::lv_obj_remove_event_cb_with_user_data(
                obj,
                Some(drop_retained_image_src),
                previous.cast::<c_void>(),
            );
            drop(Box::from_raw(previous));
        }
    }
}

unsafe extern "C" fn drop_retained_image_src(e: *mut c_bindings::lv_event_t) {
    let retained = unsafe { c_bindings::lv_event_get_user_data(e) }.cast::<ImageSrc>();
    if !retained.is_null() {
        drop_retained_ptr(retained);
    }
}

fn drop_retained_ptr(retained: *mut ImageSrc) {
    let removed = with_image_retention_store(|store| {
        let key = store
            .iter()
            .find_map(|(key, ptr)| (*ptr == retained).then_some(*key));
        key.and_then(|key| store.remove(&key))
    });
    if let Some(retained) = removed {
        unsafe {
            drop(Box::from_raw(retained));
        }
    }
}

#[cfg(test)]
pub(crate) fn retained_image_src_count() -> usize {
    with_image_retention_store(|store| store.len())
}

#[cfg(test)]
pub(crate) fn reset_retained_image_srcs() {
    let retained = with_image_retention_store(|store| {
        let retained = store.values().copied().collect::<alloc::vec::Vec<_>>();
        store.clear();
        retained
    });
    for retained in retained {
        unsafe {
            drop(Box::from_raw(retained));
        }
    }
}

// ============================================================
//  Image widget
// ============================================================

/// LVGL image widget (`lv_image`).
///
/// Displays a static image from a C array descriptor or a file-system path.
/// Supports offset, uniform scaling, and rotation around a configurable pivot.
///
/// # Kconfig requirements
/// `CONFIG_LV_USE_IMAGE=y`
///
/// # Example
/// ```ignore
/// use lvgl_dsl::lvgl::prelude::*;
///
/// // C descriptor (unsafe):
/// // extern "C" { static MY_ICON: core::ffi::c_void; }
/// let src = unsafe { ImageSrc::descriptor(&raw const MY_ICON) };
///
/// let img = Image::new(&screen)
///     .set_src(src)
///     .set_scale(256)           // 1:1 (256 = 100 %)
///     .set_rotation(0)
///     .align(LvAlign::Center, 0, 0);
///
/// // File path (safe):
/// let src = ImageSrc::file("S:icons/logo.bin")?;
///
/// let img = Image::new(&screen)
///     .set_src(src)
///     .size(Size::Px(64), Size::Px(64));
/// ```
pub struct Image {
    obj: LvObj,
}

/// Mirrors LVGL's `lv_image_align_t`. Values must match the C enum in
/// `lv_image.h` (LVGL v9).
#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum LvImageAlign {
    Default = 0,
    TopLeft = 1,
    TopMid = 2,
    TopRight = 3,
    BottomLeft = 4,
    BottomMid = 5,
    BottomRight = 6,
    LeftMid = 7,
    RightMid = 8,
    Center = 9,
    /// Independently scales X and Y to fill the widget's area. The
    /// widget's size MUST be set explicitly (auto-size to source is
    /// otherwise the default).
    Stretch = 11,
    Tile = 12,
    Contain = 13,
    Cover = 14,
}

impl Widget for Image {
    fn lv_obj(&self) -> &LvObj {
        &self.obj
    }
}

impl Image {
    /// Creates a new image widget as a child of `parent`.
    ///
    /// # Panics
    /// Panics if LVGL returns a null pointer (out-of-memory or
    /// `LV_USE_IMAGE` not enabled in Kconfig).
    pub fn new(parent: &impl Widget) -> Image {
        // SAFETY: `parent` wraps a non-null, valid LVGL object.
        let obj = unsafe { c_bindings::lv_image_create(parent.lv_obj().raw()) };
        if obj.is_null() {
            panic!("lv_image_create returned null — check CONFIG_LV_USE_IMAGE=y");
        }
        Image {
            obj: LvObj::from_raw(obj),
        }
    }

    /// Sets the image source and retains it until this LVGL object is deleted.
    pub fn set_src(&self, src: ImageSrc) -> &Self {
        let obj = self.lv_obj().raw();
        set_retained_src_for_obj(obj, ImageRetentionSlot::Source, src, |src_ptr| unsafe {
            c_bindings::lv_image_set_src(obj, src_ptr);
        });
        self
    }

    /// Shifts the image by `(x, y)` pixels relative to its normal position.
    pub fn set_offset(&self, x: i32, y: i32) -> &Self {
        unsafe {
            c_bindings::lv_image_set_offset_x(self.lv_obj().raw(), x);
            c_bindings::lv_image_set_offset_y(self.lv_obj().raw(), y);
        }
        self
    }

    /// Sets the scale factor.  `256` = 100 % (no scaling), `128` = 50 %,
    /// `512` = 200 %.
    pub fn set_scale(&self, factor: u32) -> &Self {
        unsafe { c_bindings::lv_image_set_scale(self.lv_obj().raw(), factor) };
        self
    }

    /// Sets the rotation angle in tenths of degrees.
    ///
    /// `10` units = 1°, so `900` = 90°, `3600` = 360°. Values outside
    /// 0–3600 are wrapped by LVGL. Rotation is applied around the pivot
    /// set by [`set_pivot`](Image::set_pivot).
    pub fn set_rotation(&self, angle: i32) -> &Self {
        unsafe { c_bindings::lv_image_set_rotation(self.lv_obj().raw(), angle) };
        self
    }

    /// Sets the pivot point for rotation and scaling, in pixels relative to
    /// the top-left corner of the image.
    pub fn set_pivot(&self, x: i32, y: i32) -> &Self {
        unsafe { c_bindings::lv_image_set_pivot(self.lv_obj().raw(), x, y) };
        self
    }

    /// Sets how the bitmap is positioned/sized inside the widget's bounding
    /// box. The default (`LvImageAlign::Default`) draws the bitmap at its
    /// native size from the widget's top-left. `LvImageAlign::Stretch`
    /// scales the X and Y axes independently so the bitmap fills the
    /// widget's area exactly — useful when overlays must align to a
    /// known coordinate space and the widget size is set explicitly.
    pub fn set_inner_align(&self, align: LvImageAlign) -> &Self {
        unsafe { c_bindings::lv_image_set_inner_align(self.lv_obj().raw(), align as u32) };
        self
    }

    /// Sets the tint color blended over the rendered image
    /// (`LV_PART_MAIN | LV_STATE_DEFAULT`).
    ///
    /// Has no visible effect until [`recolor_opa`](Self::recolor_opa)
    /// is set to a non-zero value. Works for any image source
    /// including SVG, since the recolor is applied on the post-decode
    /// raster while preserving alpha.
    pub fn recolor(&self, color: crate::lvgl::color::Color) -> &Self {
        unsafe {
            c_bindings::lv_obj_set_style_image_recolor(
                self.lv_obj().raw(),
                color.to_lv(),
                0,
            );
        }
        self
    }

    /// Sets the opacity of the tint color set by [`recolor`](Self::recolor)
    /// (`LV_PART_MAIN | LV_STATE_DEFAULT`).
    ///
    /// `0` keeps the original colors, `255` fully replaces them with the
    /// recolor value, intermediate values blend.
    pub fn recolor_opa(&self, opa: u8) -> &Self {
        unsafe {
            c_bindings::lv_obj_set_style_image_recolor_opa(
                self.lv_obj().raw(),
                opa,
                0,
            );
        }
        self
    }

    /// Resets the tint by setting `recolor_opa` to `0`.
    ///
    /// The recolor *color* set by [`recolor`](Self::recolor) is left
    /// untouched — it just becomes invisible. Equivalent to calling
    /// `recolor_opa(0)` but reads better at call sites that want to
    /// say "no tint right now".
    pub fn clear_recolor(&self) -> &Self {
        self.recolor_opa(0)
    }
}

// ============================================================
//  Tests
// ============================================================
#[cfg(test)]
mod tests {
    use crate::c_bindings::{LvCall, lv_obj_delete, reset_obj_pool, spy_drain};
    use crate::lvgl::image::{
        Image, ImageSrc, reset_retained_image_srcs, retained_image_src_count,
    };
    use crate::lvgl::screen::Screen;
    use crate::lvgl::widget::Widget;

    fn setup() -> Screen {
        reset_obj_pool();
        reset_retained_image_srcs();
        Screen::active()
    }

    #[test]
    fn image_create_records_spy() {
        let screen = setup();
        let _ = Image::new(&screen);
        let calls = spy_drain();
        assert!(
            calls
                .iter()
                .any(|c| matches!(c, LvCall::ImageCreate { .. })),
            "expected ImageCreate in spy: {:?}",
            calls
        );
    }

    #[test]
    fn image_set_src_records_spy() {
        let screen = setup();
        let img = Image::new(&screen);
        spy_drain(); // clear create call
        let dummy: u8 = 0;
        let src = unsafe { ImageSrc::descriptor(core::ptr::addr_of!(dummy).cast()) };
        img.set_src(src);
        let calls = spy_drain();
        assert!(
            calls
                .iter()
                .any(|c| matches!(c, LvCall::ImageSetSrc { .. })),
            "expected ImageSetSrc in spy: {:?}",
            calls
        );
    }

    #[test]
    fn image_set_src_replaces_retained_source() {
        let screen = setup();
        let img = Image::new(&screen);
        spy_drain();

        img.set_src(ImageSrc::file("S:first.png").unwrap());
        assert_eq!(retained_image_src_count(), 1);
        spy_drain();

        img.set_src(ImageSrc::file("S:second.png").unwrap());
        assert_eq!(retained_image_src_count(), 1);
        let calls = spy_drain();
        let image_set_idx = calls
            .iter()
            .position(|c| matches!(c, LvCall::ImageSetSrc { .. }))
            .expect("expected replacement ImageSetSrc call");
        let remove_idx = calls
            .iter()
            .position(|c| matches!(c, LvCall::RemoveEventCbWithUserData { .. }))
            .expect("expected previous retained source callback removal");
        assert!(
            image_set_idx < remove_idx,
            "expected LVGL source update before dropping previous retained source: {:?}",
            calls
        );
        assert!(
            calls
                .iter()
                .any(|c| matches!(c, LvCall::AddEventCb { .. })),
            "expected new retained source delete callback registration: {:?}",
            calls
        );

        unsafe {
            lv_obj_delete(img.lv_obj().raw());
        }
        assert_eq!(retained_image_src_count(), 0);
    }

    #[test]
    fn image_recolor_records_spy() {
        use crate::lvgl::color::Color;

        let screen = setup();
        let img = Image::new(&screen);
        spy_drain(); // discard ImageCreate

        img.recolor(Color::hex(0xFFFFFF));

        let calls = spy_drain();
        let recolor = calls
            .iter()
            .find_map(|c| match c {
                LvCall::SetStyleImageRecolor { color, .. } => Some(*color),
                _ => None,
            })
            .expect("expected SetStyleImageRecolor in spy");

        // lv_color_t for white must be all-FF in its byte representation;
        // we don't compare struct fields directly to avoid coupling to
        // LVGL's internal pixel format.
        let bytes: [u8; core::mem::size_of::<crate::c_bindings::lv_color_t>()] =
            unsafe { core::mem::transmute(recolor) };
        assert!(bytes.iter().all(|b| *b == 0xFF), "expected white tint, got {:?}", bytes);
    }

    #[test]
    fn image_recolor_opa_records_spy() {
        let screen = setup();
        let img = Image::new(&screen);
        spy_drain(); // discard ImageCreate

        img.recolor_opa(128);

        let calls = spy_drain();
        let opa = calls
            .iter()
            .find_map(|c| match c {
                LvCall::SetStyleImageRecolorOpa { opa, .. } => Some(*opa),
                _ => None,
            })
            .expect("expected SetStyleImageRecolorOpa in spy");
        assert_eq!(opa, 128);
    }

    #[test]
    fn image_clear_recolor_sets_opa_zero() {
        let screen = setup();
        let img = Image::new(&screen);
        spy_drain(); // discard ImageCreate

        img.clear_recolor();

        let calls = spy_drain();
        let opa = calls
            .iter()
            .find_map(|c| match c {
                LvCall::SetStyleImageRecolorOpa { opa, .. } => Some(*opa),
                _ => None,
            })
            .expect("expected SetStyleImageRecolorOpa in spy");
        assert_eq!(opa, 0, "clear_recolor should set recolor_opa to 0");
    }

    #[test]
    fn image_delete_releases_retained_source() {
        let screen = setup();
        let img = Image::new(&screen);

        img.set_src(ImageSrc::file("S:delete-me.png").unwrap());
        assert_eq!(retained_image_src_count(), 1);

        unsafe {
            lv_obj_delete(img.lv_obj().raw());
        }
        assert_eq!(retained_image_src_count(), 0);
    }

    #[test]
    fn image_set_offset_records_spy() {
        let screen = setup();
        let img = Image::new(&screen);
        spy_drain();
        img.set_offset(10, -5);
        let calls = spy_drain();
        assert!(
            calls
                .iter()
                .any(|c| matches!(c, LvCall::ImageSetOffset { x: 10, y: -5, .. })),
            "expected ImageSetOffset{{10, -5}} in spy: {:?}",
            calls
        );
    }

    #[test]
    fn image_set_scale_records_spy() {
        let screen = setup();
        let img = Image::new(&screen);
        spy_drain();
        img.set_scale(512);
        let calls = spy_drain();
        assert!(
            calls
                .iter()
                .any(|c| matches!(c, LvCall::ImageSetScale { factor: 512, .. })),
            "expected ImageSetScale{{512}} in spy: {:?}",
            calls
        );
    }

    #[test]
    fn image_set_rotation_records_spy() {
        let screen = setup();
        let img = Image::new(&screen);
        spy_drain();
        img.set_rotation(900);
        let calls = spy_drain();
        assert!(
            calls
                .iter()
                .any(|c| matches!(c, LvCall::ImageSetRotation { angle: 900, .. })),
            "expected ImageSetRotation{{900}} in spy: {:?}",
            calls
        );
    }

    #[test]
    fn image_set_pivot_records_spy() {
        let screen = setup();
        let img = Image::new(&screen);
        spy_drain();
        img.set_pivot(32, 32);
        let calls = spy_drain();
        assert!(
            calls
                .iter()
                .any(|c| matches!(c, LvCall::ImageSetPivot { x: 32, y: 32, .. })),
            "expected ImageSetPivot{{32, 32}} in spy: {:?}",
            calls
        );
    }

    #[test]
    fn image_src_file_accepts_rust_str_path() {
        let src = ImageSrc::file("S:assets/buttons/collect_icon.png").unwrap();
        assert!(!src.as_ptr().is_null());
    }

    #[test]
    fn image_src_file_rejects_interior_nul() {
        assert!(ImageSrc::file("S:bad\0path.png").is_err());
    }

    #[test]
    fn image_src_file_cstr_constructor() {
        let src = ImageSrc::file_cstr(c"/lfs/test.bin");
        assert!(!src.as_ptr().is_null());
    }

    #[test]
    fn image_chaining_returns_self() {
        let screen = setup();
        let img = Image::new(&screen);
        spy_drain();
        let dummy: u8 = 0;
        let src = unsafe { ImageSrc::descriptor(core::ptr::addr_of!(dummy).cast()) };
        let result = img
            .set_src(src)
            .set_offset(0, 0)
            .set_scale(256)
            .set_rotation(0);
        assert!(core::ptr::eq(result, &img));
    }
}
