[package]
name = "jetbeep-core"
version = "0.1.0"
edition = "2021"
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib"]

[features]
default = ["platform-desktop"]
platform-desktop = ["dep:env_logger", "dep:reqwest", "dep:url", "dep:once_cell", "dep:serde_json", "futures/std"]
platform-zephyr = ["dep:enumset", "dep:lvgl-dsl"]
simulator = ["platform-desktop"]

[dependencies]
futures = { version = "0.3", default-features = false, features = ["alloc"] }
log = "0.4"
env_logger = { version = "0.11", optional = true }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"], optional = true }
prost = { version = "0.13", default-features = false, features = ["derive"] }
crc = { workspace = true }
jkv = { path = "../jkv" }
enumset = { version = "1.1.10", optional = true }
lvgl-dsl = { path = "../lvgl-dsl", optional = true }

reqwest = { version = "0.12", features = ["json", "socks", "blocking"], optional = true }
url = { version = "2.5", optional = true }
once_cell = { version = "1.20", optional = true }


[dev-dependencies]
tempfile = "3"

[build-dependencies]
bindgen = "0.72.1"
prost-build = "0.13"
protoc-bin-vendored = "3"
